# Streamlit Configuration - Mobil App için özelleştirilmiş

[server]
headless = false
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#00E5FF"
backgroundColor = "#0b0e19"
secondaryBackgroundColor = "#1B222D"
textColor = "#e2e8f0"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"
