# Streamlit Configuration

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#00E5FF"
backgroundColor = "#0b0e19"
secondaryBackgroundColor = "#1B222D"
textColor = "#e2e8f0"
font = "sans serif"
